import {test} from 'node:test';import assert from 'node:assert/strict';import {normalize,validate,Values,visible,fields} from '../lib/form';
const good:Values={full_name:'Persona de prueba',whatsapp:'+506 8888 8888',email:'test@example.com',roles:['artist'],proposal_area:['art_creativity'],workshop_name:'Cerámica',idea:'Crearemos una taza.',audience:['adults'],duration:'undecided',group_size:'undecided',participant_experience:'no',materials:'undecided',space_needs:['table_chairs'],facilitated_before:'no',nosara_workshops:'no',collaboration:['undecided'],price_defined:'no',frequency:'undecided',community_contribution:'Creatividad.',consent:true};
test('new facilitators and undecided pricing/capacity are accepted',()=>assert.deepEqual(validate(good),{}));
test('hidden fields are not stored',()=>{const n=normalize({...good,price_estimate:'stale',previous_locations:'stale',participant_experience_details:'stale'});assert.equal(n.price_estimate,undefined);assert.equal(n.previous_locations,undefined);assert.equal(n.participant_experience_details,undefined)});
test('conditional other fields and experience detail are required',()=>{const e=validate({...good,roles:['other'],participant_experience:'yes'});assert.equal(e.role_other,'required');assert.equal(e.participant_experience_details,'required')});
test('options are normalized and invalid options rejected',()=>{assert.deepEqual(normalize({...good,roles:['artist','artist','educator']}).roles,['artist','educator']);assert.equal(validate({...good,roles:['Artista']}).roles,'invalid')});
test('length, consent and exclusive choices validated',()=>{const e=validate({...good,idea:'x'.repeat(601),consent:false,space_needs:['none','water']});assert.equal(e.idea,'too_long');assert.equal(e.consent,'required');assert.equal(e.space_needs,'invalid')});

test('venue payment terms are required only for selected models',()=>{const v={...good,collaboration:['monthly','revenue_share']};const e=validate(v);assert.equal(e.space_monthly_budget,'required');assert.equal(e.space_revenue_share,'required');assert.equal(e.space_hourly_budget,undefined);assert.deepEqual(validate({...v,space_monthly_budget:'USD 200, four sessions per month',space_revenue_share:'20% of gross revenue for the venue'}),{})});
test('local market questions and participant price details follow answers',()=>{const e=validate({...good,nosara_workshops:'yes',price_defined:'yes'});assert.equal(e.nosara_venues,'required');assert.equal(e.price_estimate,'required');assert.equal(e.participant_price_includes,'required');const n=normalize({...good,space_monthly_budget:'old',nosara_venues:'old',participant_price_includes:'old'});assert.equal(n.space_monthly_budget,undefined);assert.equal(n.nosara_venues,undefined);assert.equal(n.participant_price_includes,undefined)});
