export type Lang='es'|'en';export type Values=Record<string,string|string[]|boolean>;
type Choice={value:string;es:string;en:string};
export type Field={id:string;section:number;es:string;en:string;type:'text'|'email'|'tel'|'url'|'textarea'|'multi'|'select'|'yesno'|'checkbox';required?:boolean;max?:number;options?:Choice[];when?:[string,string];help?:{es:string;en:string};exclusive?:string[]};
const opts=(rows:string[][]):Choice[]=>rows.map(([value,es,en])=>({value,es,en}));
export const fields:Field[]=[
{id:'full_name',section:0,es:'Nombre completo',en:'Full name',type:'text',required:true,max:120},
{id:'project_name',section:0,es:'Nombre de tu emprendimiento, proyecto o marca',en:'Business, project or brand name',type:'text',max:160},
{id:'whatsapp',section:0,es:'WhatsApp',en:'WhatsApp',type:'tel',required:true,max:30},
{id:'email',section:0,es:'Correo electrónico',en:'Email address',type:'email',required:true,max:254},
{id:'portfolio',section:0,es:'Instagram, página web o portafolio',en:'Instagram, website or portfolio',type:'text',max:300},
{id:'roles',section:0,es:'¿Cómo te describes?',en:'How would you describe yourself?',type:'multi',required:true,options:opts([['artist','Artista','Artist'],['entrepreneur','Emprendedor(a)','Entrepreneur'],['artisan','Artesano(a)','Artisan'],['workshop_leader','Tallerista','Workshop leader'],['wellness_professional','Profesional de bienestar','Wellbeing professional'],['educator','Educador(a)','Educator'],['facilitator','Facilitador(a)','Facilitator'],['other','Otro','Other']])},
{id:'role_other',section:0,es:'Cuéntanos cuál',en:'Please specify',type:'text',required:true,max:120,when:['roles','other']},
{id:'proposal_area',section:1,es:'¿Qué tipo de experiencia te gustaría compartir?',en:'What kind of experience would you like to share?',type:'multi',required:true,options:opts([['art_creativity','Arte & creatividad','Art & creativity'],['kids_families','Niños & familias','Children & families'],['wellness','Bienestar','Wellbeing'],['culture','Cultura & conversaciones','Culture & conversations'],['nature','Naturaleza & sostenibilidad','Nature & sustainability'],['experiences','Experiencias & celebraciones','Experiences & celebrations'],['other','Otro','Other']])},
{id:'proposal_area_other',section:1,es:'¿Qué otra experiencia?',en:'What other experience?',type:'text',required:true,max:120,when:['proposal_area','other']},
{id:'workshop_name',section:1,es:'¿Cómo llamarías a tu taller o experiencia?',en:'What would you call your workshop or experience?',type:'text',required:true,max:160,help:{es:'Por ejemplo: Cerámica & vino, Pintura para niños, Creación de velas o Círculo de mujeres.',en:'For example: Pottery & wine, Painting for children, Candle making or Women’s circle.'}},
{id:'idea',section:1,es:'Cuéntanos brevemente tu idea',en:'Briefly tell us about your idea',type:'textarea',required:true,max:600,help:{es:'¿Qué harán, aprenderán o crearán los participantes?',en:'What will participants do, learn or create?'}},
{id:'audience',section:2,es:'¿Para quién está pensada?',en:'Who is it for?',type:'multi',required:true,exclusive:['everyone'],options:opts([['children','Niños','Children'],['teens','Adolescentes','Teenagers'],['adults','Adultos','Adults'],['families','Familias','Families'],['couples','Parejas','Couples'],['friends','Grupos de amigos','Groups of friends'],['companies','Empresas / equipos','Companies / teams'],['everyone','Abierto a todos','Everyone']])},
{id:'duration',section:2,es:'¿Cuál sería la duración aproximada?',en:'Approximately how long would it last?',type:'select',required:true,options:opts([['under_1h','Menos de 1 hora','Less than 1 hour'],['1_2h','1–2 horas','1–2 hours'],['2_3h','2–3 horas','2–3 hours'],['over_3h','Más de 3 horas','More than 3 hours'],['undecided','Aún no lo tengo definido','Not sure yet']])},
{id:'group_size',section:2,es:'¿Para cuántas personas funciona mejor?',en:'What group size works best?',type:'select',required:true,options:opts([['1_5','1–5','1–5'],['6_10','6–10','6–10'],['11_15','11–15','11–15'],['16_20','16–20','16–20'],['over_20','Más de 20','More than 20'],['undecided','Aún no lo tengo definido','Not sure yet']])},
{id:'participant_experience',section:2,es:'¿Los participantes necesitan experiencia previa?',en:'Do participants need previous experience?',type:'yesno',required:true},
{id:'participant_experience_details',section:2,es:'¿Qué experiencia necesitan?',en:'What experience do they need?',type:'text',required:true,max:250,when:['participant_experience','yes']},
{id:'materials',section:2,es:'¿Los materiales están incluidos en tu propuesta?',en:'Are materials included in your proposal?',type:'select',required:true,options:opts([['all','Sí, yo proporciono todos los materiales','Yes, I provide all materials'],['some','Algunos materiales','Some materials'],['none','No','No'],['depends','Depende de la experiencia','It depends on the experience'],['undecided','Aún no lo tengo definido','Not sure yet']])},
{id:'space_needs',section:2,es:'¿Necesitas algo especial del espacio?',en:'Do you need anything specific from the space?',type:'multi',required:true,exclusive:['none'],options:opts([['table_chairs','Mesa y sillas','Table and chairs'],['water','Agua / fregadero','Water / sink'],['electricity','Electricidad','Electricity'],['outdoors','Espacio exterior','Outdoor space'],['projector','Proyector / pantalla','Projector / screen'],['sound','Sonido / música','Sound / music'],['food_area','Área para alimentos','Food area'],['other','Otro','Other'],['none','Nada especial','Nothing specific']])},
{id:'space_needs_other',section:2,es:'¿Qué más necesitas?',en:'What else do you need?',type:'text',required:true,max:250,when:['space_needs','other']},
{id:'facilitated_before',section:3,es:'¿Has impartido este taller o una experiencia similar antes?',en:'Have you led this workshop or a similar experience before?',type:'yesno',required:true,help:{es:'Las ideas nuevas también son bienvenidas.',en:'New ideas are welcome too.'}},
{id:'previous_locations',section:3,es:'¿Dónde lo has realizado?',en:'Where have you offered it?',type:'text',max:250,when:['facilitated_before','yes']},
{id:'previous_portfolio',section:3,es:'¿Tienes fotografías, Instagram o algún material que podamos ver?',en:'Do you have photos, Instagram or material we can look at?',type:'url',max:500,when:['facilitated_before','yes']},
{id:'collaboration',section:4,es:'¿Cómo te gustaría trabajar con El Taller?',en:'How would you like to collaborate with El Taller?',type:'multi',required:true,options:opts([['revenue_share','Recibir un porcentaje por participante','Receive a share per participant'],['fixed_fee','Cobrar una tarifa fija por impartir el taller','Charge a fixed workshop fee'],['rent_space','Alquilar el espacio','Rent the space'],['co_create','Crear la experiencia en conjunto con El Taller','Create the experience with El Taller'],['flexible','Estoy abierto(a) a diferentes opciones','I am open to different options'],['undecided','No estoy seguro(a) todavía','I am not sure yet']])},
{id:'price_defined',section:4,es:'¿Ya tienes definido cuánto cobrarías?',en:'Have you decided how much you would charge?',type:'yesno',required:true},
{id:'price_estimate',section:4,es:'Indícanos tu tarifa o precio estimado',en:'Tell us your estimated rate or price',type:'text',max:160,when:['price_defined','yes'],help:{es:'Incluye moneda y modalidad. Ej.: ₡25.000 por persona o $150 por taller.',en:'Include currency and basis. E.g. ₡25,000 per person or $150 per workshop.'}},
{id:'frequency',section:4,es:'¿Con qué frecuencia te interesaría realizar actividades?',en:'How often would you like to offer activities?',type:'select',required:true,options:opts([['once','Una única experiencia','One experience'],['monthly','Una vez al mes','Once a month'],['several_monthly','Varias veces al mes','Several times a month'],['weekly','Semanalmente','Weekly'],['seasonal','Por temporadas','Seasonally'],['demand','Depende de la demanda','Depending on demand'],['undecided','Aún no lo sé','Not sure yet']])},
{id:'community_contribution',section:5,es:'¿Qué te gustaría aportar a la comunidad de El Taller?',en:'What would you like to bring to the El Taller community?',type:'textarea',required:true,max:400,help:{es:'Puede ser creatividad, conocimiento, bienestar, conexión, aprendizaje, diversión...',en:'Creativity, knowledge, wellbeing, connection, learning, fun...'}},
{id:'referral',section:5,es:'¿Cómo conociste El Taller?',en:'How did you hear about El Taller?',type:'select',options:opts([['instagram','Instagram','Instagram'],['whatsapp','WhatsApp','WhatsApp'],['recommendation','Recomendación de alguien','A recommendation'],['flyer_qr','Flyer / QR','Flyer / QR'],['event','Evento','Event'],['walkby','Pasé por el espacio','I passed by the space'],['other','Otro','Other']])},
{id:'referral_other',section:5,es:'¿Dónde nos conociste?',en:'Where did you hear about us?',type:'text',max:120,when:['referral','other']},
{id:'consent',section:5,es:'Confirmo que la información proporcionada es correcta y autorizo a El Taller a contactarme para conversar sobre esta propuesta.',en:'I confirm that the information provided is correct and authorise El Taller to contact me to discuss this proposal.',type:'checkbox',required:true}
];
export function visible(f:Field,v:Values){if(!f.when)return true;const value=v[f.when[0]];return Array.isArray(value)?value.includes(f.when[1]):value===f.when[1]}
export function normalize(v:Values):Values {const out:Values={};for(const f of fields){if(!visible(f,v))continue;const val=v[f.id];if(f.type==='multi')out[f.id]=Array.isArray(val)?[...new Set(val)].sort():[];else if(f.type==='checkbox')out[f.id]=val===true;else out[f.id]=typeof val==='string'?val.trim():'';}return out}
export function validate(v:Values,section?:number){const errors:Record<string,string>={};for(const f of fields){if(section!==undefined&&f.section!==section||!visible(f,v))continue;const value=v[f.id];const empty=value===undefined||value===false||value===''||typeof value==='string'&&!value.trim()||Array.isArray(value)&&value.length===0;if(f.required&&empty){errors[f.id]='required';continue}if(empty)continue;if(f.type==='multi'){if(!Array.isArray(value)||value.some(x=>!f.options?.some(o=>o.value===x))||f.exclusive?.some(x=>value.includes(x)&&value.length>1))errors[f.id]='invalid';}else if(f.type==='checkbox'){if(value!==true)errors[f.id]='required';}else if(typeof value!=='string'){errors[f.id]='invalid';}else if(f.max&&value.length>f.max){errors[f.id]='too_long';}else if(f.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)){errors[f.id]='email';}else if(f.type==='tel'&&!/^\+?[\d\s().-]{7,30}$/.test(value)){errors[f.id]='phone';}else if(f.type==='url'){try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol))errors[f.id]='url'}catch{errors[f.id]='url'}}else if(f.type==='select'&&!f.options?.some(o=>o.value===value)||f.type==='yesno'&&!['yes','no'].includes(value)){errors[f.id]='invalid'}}return errors}
