import {createSign} from 'node:crypto';import {fields,Values} from './form';
export const columns=['submission_id','created_at','language',...fields.map(f=>f.id)];
export function sheetRow(id:string,language:string,values:Values){return [id,new Date().toISOString(),language,...fields.map(f=>{const v=values[f.id];return Array.isArray(v)?v.join('|'):typeof v==='boolean'?String(v):v||''})]}
let tokenCache:{token:string;expires:number}|undefined;
async function accessToken(){if(tokenCache&&tokenCache.expires>Date.now())return tokenCache.token;const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n');if(!email||!key)throw new Error('not_configured');const now=Math.floor(Date.now()/1000),encode=(v:object)=>Buffer.from(JSON.stringify(v)).toString('base64url');const jwt=encode({alg:'RS256',typ:'JWT'})+'.'+encode({iss:email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});const signature=createSign('RSA-SHA256').update(jwt).sign(key,'base64url');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt+'.'+signature}),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('auth_failed');const data=await r.json();tokenCache={token:data.access_token,expires:Date.now()+3300000};return tokenCache.token}
export function sheetsConfigured(){return !!(process.env.GOOGLE_SHEET_ID&&process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL&&process.env.GOOGLE_PRIVATE_KEY)}
export async function appendProposal(id:string,language:string,values:Values){const token=await accessToken();const sheet=process.env.GOOGLE_SHEET_TAB||'Propuestas';const range="'"+sheet.replace(/'/g,"''")+"'!A:AZ";const base=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(process.env.GOOGLE_SHEET_ID!)}/values/`;const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
// Repeated attempts with the same browser submission ID return the already saved result.
const ids=await fetch(base+encodeURIComponent("'"+sheet.replace(/'/g,"''")+"'!A:A"),{headers,signal:AbortSignal.timeout(12000)});if(!ids.ok)throw new Error('sheet_unavailable');const existing=await ids.json();if(existing.values?.some((row:string[])=>row[0]===id))return;
if(!existing.values?.length){const init=await fetch(base+encodeURIComponent("'"+sheet.replace(/'/g,"''")+"'!A1")+'?valueInputOption=RAW',{method:'PUT',headers,body:JSON.stringify({values:[columns]}),signal:AbortSignal.timeout(12000)});if(!init.ok)throw new Error('headers_failed')}
const r=await fetch(base+encodeURIComponent(range)+':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS',{method:'POST',headers,body:JSON.stringify({values:[sheetRow(id,language,values)]}),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('append_failed')}
